version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nginx:
    build: nginx/
    ports:
        - "883:80"
    depends_on:
      tomcat:
        condition: service_healthy
    volumes: 
       - ./html:/opt/app/


  tomcat:  
    build: ./tomcat
    ports:
      - "8081:8080"
    links:
      - postgres
  
